parse_config:

  # zmk_combos:
  #   lbkt: {draw_separate: true}
  #   rbkt: {draw_separate: true}
  #   lpar: {draw_separate: true}
  #   rpar: {draw_separate: true}
  #   lbrc: {draw_separate: true}
  #   rbrc: {draw_separate: true}
  #   del: {draw_separate: true}
  #   esc: {draw_separate: true}
  #   ins: {draw_separate: true}
  #   bpsc: {draw_separate: true} 
  #   pscn: {draw_separate: true}

  raw_binding_map:
    '&soft_off': Soft Off
    '&caps_word': Caps Word
  
  zmk_keycode_map:
    # custom mappings
    LCTRL: Ctrl
    LEFT_ALT: Alt
    LALT: Alt
    LGUI: Gui
    LEFT_GUI: Gui
    LSHFT: Shift
    LEFT_SHIFT: Shift
    ESC: Esc
    SPACE: ␣
    BSPC: ⌫
    BACKSPACE: ⌫
    RET: ⏎
    TAB: ↹
    DEL: ⌦

    INS: Insert
    HOME: Home
    END: End
    CAPS: Caps Lock
    PSCRN: Prnt Scrn
    PRINTSCREEN: Prnt Scrn
    PAUSE_BREAK: Pause Break

    UP: ↑
    DOWN: ↓
    LEFT: ←
    RIGHT: →

    LC(TAB): Tab →
    LC(LS(TAB)): Tab ←
    LA(F4): Win Close
    LC(F4): Tab Close
    LS(TAB): Win Prev
    LS(INS): Paste
    LC(LS(V)): Plain P
    LC(C): Copy
    LC(X): Cut
    LC(Z): Undo
    LC(A): Select All
    LG(L): Lock

    # defaults
    AMPERSAND: '&'
    AMPS: '&'
    APOS: "'"
    APOSTROPHE: "'"
    ASTERISK: '*'
    ASTRK: '*'
    AT: '@'
    AT_SIGN: '@'
    BACKSLASH: \
    BSLH: \
    CARET: ^
    COLON: ':'
    COMMA: ','
    DLLR: $
    DOLLAR: $
    DOT: .
    DOUBLE_QUOTES: '"'
    DQT: '"'
    EQUAL: '='
    EXCL: '!'
    EXCLAMATION: '!'
    FSLH: /
    GRAVE: '`'
    GREATER_THAN: '>'
    GT: '>'
    HASH: '#'
    LBKT: '['
    LBRC: '{'
    LEFT_BRACE: '{'
    LEFT_BRACKET: '['
    LEFT_PARENTHESIS: (
    LESS_THAN: <
    LPAR: (
    LT: <
    MINUS: '-'
    NON_US_BACKSLASH: \
    NON_US_BSLH: '|'
    NON_US_HASH: '#'
    NUHS: '#'
    PERCENT: '%'
    PERIOD: .
    PIPE: '|'
    PIPE2: '|'
    PLUS: +
    POUND: '#'
    PRCNT: '%'
    QMARK: '?'
    QUESTION: '?'
    RBKT: ']'
    RBRC: '}'
    RIGHT_BRACE: '}'
    RIGHT_BRACKET: ']'
    RIGHT_PARENTHESIS: )
    RPAR: )
    SEMI: ;
    SEMICOLON: ;
    SINGLE_QUOTE: ''''
    SLASH: /
    SQT: ''''
    STAR: '*'
    TILDE: '~'
    TILDE2: '~'
    UNDER: _
    UNDERSCORE: _